language: python
sudo: required
python:
  - "2.7"
# command to install dependencies
addons:
  sauce_connect:
    username: "nengo"
    access_key: "21faaee4-a99e-4b40-bc89-23170618ff0e"
install: 
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - "nengo_gui"#starts up nengo_gui
  - sleep 2
# command to run tests
script: py.test