language: python
sudo: required
python:
  - "2.7"
# command to install dependencies
addons:
  sauce_connect:
    username: "nengo"
    access_key: 
      secure: "VfbW4RTc8TY81pZ4j9DWreebIYzsm+L7eVSOgs+F2sFuTa4zbaiVl6ym7jr2SJSWLVALYzJO0IsSHrKOSjMoZYCWakhiOyoedcOQqwej8uBSE4cxTig4LaxNQJfKsW8NvxScyP38q6ZsnMPYsrKg1zXkD/b5ztLFuL6z20bMaYQ="

install: 
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
before_script:
  - npm install
  - "python setup.py develop"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - "nengo_gui &"#starts up nengo_gui
  - sleep 3
# command to run tests
script: 
  -py.test
  -node_modules/karma/bin/karma start my.conf.js --single-run