language: python
sudo: required
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - sleep 4
# command to run tests
script: py.test